# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

fastlane_version "2.105.2"

default_platform(:ios)

platform :ios do

  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :tests do
    scan(
      scheme: "EasySimulator",
      clean: true,
      code_coverage: true,
      device: "iPhone XR")
    slather(
      output_directory: "slather_output",
      workspace: "EasySimulator.xcworkspace",
      scheme: "EasySimulator",
      proj: "EasySimulator.xcodeproj",
      html: true,
      show: true)
  end
end
